
version: '2.1'

services:

  image-mongo:
    image: mongo:3.6
    container_name: image-mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
      - "27020:27017"
    command: mongod --smallfiles
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "echo 'db.runCommand(\"ping\").ok' | mongo localhost:27017/test --quiet"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - data-volume:/s3
    networks:
      - backend

  image-s3stub:
    build:
      context: ./s3
      dockerfile: ./Dockerfile
    working_dir: /
    volumes:
      - ./:/s3
    expose:
      - 4569
    ports:
      - "4569:4569"
    restart: "on-failure:10"
    environment:
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4569/"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  data-volume:

networks:
  backend:
