
version: '2.1'

services:

  image-api-test:
    build:
      context: ./tests
      dockerfile: ./Dockerfile
    working_dir: /
    restart: "on-failure:10"
    environment:
      APP_ROOT: http://image-api:3000/v1
      MONGO_CONNECTION: mongodb://image-mongo:27017
      S3LOCATION: http://image-s3stub:4569
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

    networks:
      - backend
    links:
      - image-api
      - image-s3stub
      - image-mongo
    depends_on:
      image-api:
        condition: service_healthy
      image-s3stub:
        condition: service_healthy
      image-mongo:
        condition: service_healthy
    tty: true
    command: npm run test
